# Generated by Django 5.2.17 on 2026-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
