# Generated by Django 5.2.17 on 2026-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinterBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(upload_to='winter_bikes/')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
