# Generated by Django 5.2.17 on 2026-09-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_winterbike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipment/')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
    ]
