# Generated by Django 5.2.17 on 2026-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
    ]
