# Generated by Django 5.2.17 on 2026-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_equipment_is_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('tag', models.CharField(default='#обзор', max_length=50)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
