# Generated by Django 5.2.17 on 2026-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
