# Generated by Django 5.2.17 on 2026-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_review_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
