# Generated by Django 5.2.12 on 2026-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_review_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='winterbike',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
