# Generated by Django 5.2.17 on 2026-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_winterbike_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winterbike',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
