# Generated by Django 5.2.17 on 2026-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_winterbike_is_sold_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=True, verbose_name='Продан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='winterbike',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
