# Generated by Django 5.2.17 on 2026-09-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_equipment_is_sold_alter_product_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='winterbike',
            name='price',
            field=models.IntegerField(),
        ),
    ]
