# Generated by Django 5.2.17 on 2026-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_product_detail_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='equipment/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, default='', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='reviews/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=models.CharField(default='#обзор', max_length=50, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='winterbike',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='winterbike',
            name='image',
            field=models.ImageField(upload_to='winter_bikes/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='winterbike',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='winterbike',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
