# Generated by Django 5.2.17 on 2026-09-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_equipment_image_alter_equipment_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brake_system',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Тормозная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тип тормозов'),
        ),
        migrations.AddField(
            model_name='product',
            name='chain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Цепь'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='product',
            name='crankset',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Система шатунов'),
        ),
        migrations.AddField(
            model_name='product',
            name='fork',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Вилка'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Рама'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_material',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Материал рамы'),
        ),
        migrations.AddField(
            model_name='product',
            name='handlebar',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Руль'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_derailleur',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Задний переключатель'),
        ),
        migrations.AddField(
            model_name='product',
            name='saddle',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Седло'),
        ),
        migrations.AddField(
            model_name='product',
            name='seatpost',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Подседельный штырь'),
        ),
        migrations.AddField(
            model_name='product',
            name='shifters',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Манетки'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='speeds',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Количество скоростей'),
        ),
        migrations.AddField(
            model_name='product',
            name='stem',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Вынос'),
        ),
        migrations.AddField(
            model_name='product',
            name='tires',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Покрышки'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_size',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Диаметр колеса'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheels',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Колеса'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Год'),
        ),
    ]
