# Generated by Django 5.2.17 on 2026-09-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_fill_product_characteristic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
    ]
